services:

  - type: web

    name: realtime-voice-ai-agent

    env: docker

    plan: free

    autoDeploy: true

    healthCheckPath: /

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: MODEL_NAME
        value: llama-3.1-8b-instant

      - key: WHISPER_MODEL
        value: small